name = "Hammer"
precompileModules = true
preferReleaseBuild = true
defaultTargets = ["Hammer"]

[[require]]
name = "«premise-selection»"
git = "https://github.com/hanwenzhu/premise-selection"
rev = "v4.33.0"

[[require]]
name = "«aesop»"
git = "https://github.com/leanprover-community/aesop"
rev = "v4.33.0"

[[require]]
name = "«Smt»"
git = "https://github.com/ufmg-smite/lean-smt.git"
rev = "e87b5c9c88eaf669f3cb85c73a6e75972a9c1018" # no_mathlib branch

[[require]]
name = "«Duper»"
git = "https://github.com/leanprover-community/duper.git"
rev = "34f6d228626adf1921f9fb314b0b6bd02c1a82b5"

[[lean_lib]]
name = "Hammer"
