import Lean

open Lean Meta Parser Elab Tactic Syntax

namespace HammerCore

def throwSimpPreprocessingError [Monad m] [MonadError m] (e : Exception) : m α :=
  throwError "hammer encountered an error during simp preprocessing. Try calling hammer with the simpTarget option set to no_target. Error: {e.toMessageData}"

def throwTranslationError [Monad m] [MonadError m] (e : Exception) : m α :=
  throwError "hammer failed to preprocess facts for translation. Error: {e.toMessageData}"

def throwExternalSolverError [Monad m] [MonadError m] (e : Exception) : m α :=
  throwError "hammer successfully translated the problem to TPTP, but the external prover was unable to solve it. Error: {e.toMessageData}"

def throwDuperError [Monad m] [MonadError m] (e : Exception) : m α :=
  throwError "hammer successfully translated the problem to TPTP and obtained an unsat core from an external prover, but was unable to reconstruct the proof. Error: {e.toMessageData}"

def throwProofFitError [Monad m] [MonadError m] (e : Exception) : m α :=
  throwError "hammer successfully translated the problem and reconstructed an external prover's proof, but encountered an issue in applying said proof. Error: {e.toMessageData}"

/-- A function to determine whether an error thrown by `hammer` was generated by `throwSimpPreprocessingError` -/
def errorIsSimpPreprocessingError (e : Exception) : IO Bool := do
  let eStr ← e.toMessageData.toString
  return "hammer encountered an error during simp preprocessing. Try calling hammer with the simpTarget option set to no_target.".isPrefixOf eStr

/-- A function to determine whether an error thrown by `hammer` was generated by `throwTranslationError` -/
def errorIsTranslationError (e : Exception) : IO Bool := do
  let eStr ← e.toMessageData.toString
  return "hammer failed to preprocess facts for translation.".isPrefixOf eStr

/-- A function to determine whether an error thrown by `hammer` was generated by `throwExternalSolverError` -/
def errorIsExternalSolverError (e : Exception) : IO Bool := do
  let eStr ← e.toMessageData.toString
  return "hammer successfully translated the problem to TPTP, but the external prover was unable to solve it.".isPrefixOf eStr

/-- A function to determine whether an error thrown by `hammer` was generated by `throwDuperError` -/
def errorIsDuperSolverError (e : Exception) : IO Bool := do
  let eStr ← e.toMessageData.toString
  return "hammer successfully translated the problem to TPTP and obtained an unsat core from an external prover, but was unable to reconstruct the proof.".isPrefixOf eStr

/-- A function to determine whether an error thrown by `hammer` was generated by `throwProofFitError` -/
def errorIsProofFitError (e : Exception) : IO Bool := do
  let eStr ← e.toMessageData.toString
  return "hammer successfully translated the problem and reconstructed an external prover's proof, but encountered an issue in applying said proof.".isPrefixOf eStr

end HammerCore
